ch:(server)-welcome-route
atlp-rwanda/cabal-phantom-backend pull request #1
Opened 2020-09-22 12:04 UTC by Niyiragira

** What does this PR do? 
Requests to merge ch-setup-server-welcome-ZM0sHy6Z with develop
 Description of Task to be completed?
Adding basic chores and a running server with ES6 code
How should this be manually tested?
Cloning into ones local PC and using POSTMAN
What are the relevant pivotal tracker stories?

https://trello.com/c/FMtr8tcx/23-set-up-nodejs-rest-api-empty-project

2020-09-22 13:00 UTC, ncutixavier submitted a review, later dismissed
You did good for the code. But next time you have to write a good PR that is easy to read like inserting a space at the end of paragraph.

2020-09-23 09:12 UTC, Nkbtemmy commented
you did great job but your PR description is not describing well how it will be reviewed; try to improve and also i ask you if you may put project setup in folder

2020-09-23 09:14 UTC, Nkbtemmy approved these changes, later dismissed

2020-09-23 15:35 UTC, karigirwa approved these changes

2020-09-23 19:03 UTC, ncutixavier approved these changes
Try to change the extension of eslint to json, it will make easy to read

2020-09-24 07:02 UTC, Nkbtemmy commented
Again you did great job but there same missing information in your PR description of how people will test your work (like you don't mention how reviews will test Swagger documentation ) and you are saying that we have to clone your branch that will not be correct because you clone repo not branch and you cannot clone repo witch is not merged

2020-09-24 07:19 UTC, Niyiragira commented
> Again you did great job but there same missing information in your PR description of how people will test your work (like you don't mention how reviews will test Swagger documentation ) and you are saying that we have to clone your branch that will not be correct because you clone repo not branch and you cannot clone repo witch is not merged

Thanks the issue have been corrected

2020-09-24 08:02 UTC, Nkbtemmy approved these changes

2020-09-24 09:01 UTC, blaise82 requested changes
Please do change your PR title to the proper format and improve your PR description

2020-09-24 09:01 UTC, blaise82 commented on .babelrc
> +}
add a new line

2020-09-24 09:01 UTC, blaise82 commented on src/app.js
> +// eslint-disable-next-line no-undef
do not disable any eslint rules

2020-09-24 09:01 UTC, blaise82 commented on src/app.js
> +
add body parser express

2020-09-24 09:01 UTC, blaise82 commented on src/app.js
> +app.listen(PORT, console.log(`Server started on port ${PORT}`))
please make sure that your eslint is working properly
to avoid the new line issue

2020-09-24 09:01 UTC, blaise82 commented on src/app.js
> +app.use("/welcomes",welcomeRoute);
you shouldn't be having this in the app.js file
it should be in the routes folder

2020-09-24 09:01 UTC, blaise82 commented on src/utils/swagger.js
> +        servers: ["http://localhost:5000"]
add the Heroku server

2020-09-24 09:01 UTC, blaise82 commented on src/utils/swagger.js
> +  export default swaggerOptions;
add a  new line

2020-09-24 09:02 UTC, blaise82 commented
make sure that you have one commit

2020-09-24 15:07 UTC, closed without merging