#IMQiZKj6 Logout from account
atlp-rwanda/cabal-phantom-backend pull request #13
Opened 2020-10-05 13:29 UTC by karigirwa

**What about this PR?**
This PR is about to fix setup Logout account

**Description of Task to be completed**

- Authenticated user should be able to logout.

- Authenticated user should be able to access protected resourses/URLs

- Appropriate error messages are displayed on unsuccessful attempts

**How should be manually tested?**

- Clone the repo

- Checkout the branch  ft-logout-IMQiZKj6

- Install all packages

- It can be tested in Postman

**Relevant pivots tracker**

IMQiZKj6

2020-10-18 19:58 UTC, Nkbtemmy requested changes

2020-10-18 19:58 UTC, Nkbtemmy commented on src/test/jwt.test.js
> +});
remember to add new line

2020-10-18 19:58 UTC, Nkbtemmy commented on src/Middleware/Auth.js
> +// }
new line required

2020-10-20 20:11 UTC, ceelogre commented
To be revisited in the frontend.

2020-12-14 10:32 UTC, Nkbtemmy commented
how can i test this task functionality, while you don't write its documentation ????

2020-12-16 07:18 UTC, Niyiragira submitted a review, later dismissed

2020-12-16 10:03 UTC, ceelogre requested changes

2020-12-16 10:03 UTC, ceelogre commented on src/controller/userControllers.js
> +      localStorage.removeItem("token");
localstorage should remain a browser implementation. Remove it from backend.

2020-12-16 10:03 UTC, ceelogre commented on src/middleware/protectRoutes.js
> +    let token = localStorage.getItem('token')
See previous review comment.

2020-12-16 11:45 UTC, ceelogre requested changes

2020-12-16 11:45 UTC, ceelogre commented on src/middleware/protectRoutes.js
> +import localStorage from 'localStorage'
What are you using localstorage for?

2020-12-16 13:53 UTC, ceelogre approved these changes

2020-12-22 11:38 UTC, ncutixavier approved these changes

2020-12-22 13:15 UTC, Niyiragira commented
When I use the token to get data from the protected routes, I still get data. I should  not.

2020-12-22 13:47 UTC, Nkbtemmy requested changes
This PR was good but you can still access protected routers after you logout

2020-12-23 09:38 UTC, Niyiragira approved these changes

2020-12-23 11:57 UTC, Nkbtemmy approved these changes

2020-12-23 12:47 UTC, blaise82 approved these changes

2020-12-23 12:48 UTC, merged