#9JpkBREJ ft-register-drivers-and-operators-with proper validations
atlp-rwanda/cabal-phantom-backend pull request #17
Opened 2020-10-15 16:25 UTC by Niyiragira

2020-10-15 19:23 UTC, Nkbtemmy commented
Why your PR doesn't deployed ?????

2020-10-16 06:19 UTC, Niyiragira commented
> Why your PR doesn't deployed ?????

I don't get it too. May it be may mistake?

2020-10-21 08:10 UTC, Nkbtemmy commented on src/language/locales/en.json
> +}
new line required

2020-10-21 08:11 UTC, Nkbtemmy commented on src/language/locales/rw.json
> +}
Also here

2020-10-21 08:12 UTC, Nkbtemmy commented on src/utils/generateDefaultRole.js
> +}
new line here required

2020-10-21 08:14 UTC, Nkbtemmy requested changes
You have to add new lines where are required

2020-10-21 08:21 UTC, Nkbtemmy approved these changes

2020-10-21 09:36 UTC, ceelogre requested changes
Look at the picture below about the date issue we've discussed on a call.
![Capture d’écran 2020-10-21 à 11 20 27](https://user-images.githubusercontent.com/5022823/96701837-54deb800-1391-11eb-9763-5c38f10c094b.png)

Also, although you've added lots of test cases (which is a good thing), you need to greatly improve your checks/assertions as I've mentioned in the comment.

Great work on password generation, your work is almost ready, it should be merged today.

2020-10-21 09:36 UTC, ceelogre commented on package.json
>      "bcryptjs": "^2.4.3",
Why both bcrypt and bycryptjs?

2020-10-21 09:36 UTC, ceelogre commented on src/controller/userControllers.js
> +                return false
Where will this value be received?

2020-10-21 09:36 UTC, ceelogre commented on src/test/testRegister.js
> +      });
You cannot have all these tests checking only for status code (400). Please add more checks, for example, the error messages in the response body.

2020-10-21 09:36 UTC, ceelogre commented on src/utils/generatePassword.js
> +}
It's good you're not relying on an external library to generate a password.

2020-10-21 13:37 UTC, ncutixavier approved these changes

2020-10-21 13:56 UTC, ceelogre approved these changes

2020-10-21 13:56 UTC, merged