#G7j46apS-FT(Backend)Assign driver to buses
atlp-rwanda/cabal-phantom-backend pull request #23
Opened 2020-11-01 06:26 UTC by karigirwa

**What does this PR do?**
This PR is for assigning driver to buses

**Description of Task to be completed?**

- Operator should be able to assign driver to a bus

- The driver should receive a bus assignment and unassignment email & in-app notifications.

- The operator should be able to view a paginated list of driver to bus assignments

**How should this be manually tested?**

- Clone this repo if you don't have it

- Type `git checkout origin/ft-assign-driver-to-buses#G7j46apS`

- Type `npm run dev` and `npm run migrate DB`

- Open Postman and login(POST http://localhost:5000/api/v1/auth/login) as admin with this credentials {"email": "admin@phantom.com","password":"admin"}

- In Postman assign driver to bus(PATCH http://localhost:5000/api/v1/buses/assigndriver/2) 

- In Postman unassigned driver to bus(PATCH http://localhost:5000/api/v1/buses/unassigndriver/2)

- In Postman getting a paginated list of driver to bus assignment(GET http://localhost:5000/api/v1/buses/assignedbuses)

**What are the relevant pivotal tracker stories?**
#G7j46apS

**Screenshots (if appropriate)**
<img width="960" alt="tst1" src="https://user-images.githubusercontent.com/68014898/97796503-63dc2a80-1c1b-11eb-8f45-c37961c25e07.png">
<img width="960" alt="tst2" src="https://user-images.githubusercontent.com/68014898/97796510-7191b000-1c1b-11eb-91e0-51b71df3adb5.png">
<img width="960" alt="tst3" src="https://user-images.githubusercontent.com/68014898/97796514-7a828180-1c1b-11eb-9c09-5204b3ee7ce5.png">

2020-11-01 07:43 UTC, Nkbtemmy requested changes
You have more than one commits and there few new lines required

2020-11-01 07:44 UTC, Nkbtemmy commented
Remember to rebase

2020-11-03 12:58 UTC, ncutixavier approved these changes

2020-11-03 12:59 UTC, Nkbtemmy approved these changes

2020-11-03 13:00 UTC, Niyiragira approved these changes

2020-11-04 06:40 UTC, ceelogre requested changes
Your work is almost finished, look at how you are setting language settings in the screenshot below cause when I set it to `fr` or `rw` it still returns english. Also. look at the commented out code.
![Capture d’écran 2020-11-04 à 08 34 02](https://user-images.githubusercontent.com/5022823/98077628-460c0100-1e79-11eb-9982-eac7840bde8c.png)

2020-11-04 06:40 UTC, ceelogre commented on src/controller/busControllers.js
> +                                 console.log(bus)
remove log messages. Should only be used in development.

2020-11-04 06:40 UTC, ceelogre commented on src/controller/busControllers.js
> +                    });
This section is similar to the one in `assignDriver` with a few differences. Can you refactor this into a re-usable function?

2020-11-04 06:40 UTC, ceelogre commented on src/controller/userControllers.js
> +        //console.log('payload=',payload)
No commented-out log lines. Remove them.

2020-11-04 06:40 UTC, ceelogre commented on src/test/testAssign.js
> +                        done();
You should not only `expect` for statusCode, you should check for other attributes for example the return `message`

2020-11-04 06:40 UTC, ceelogre commented on src/test/testUtils.js
> +        expect(message.signupEmail(email,password)).to.be.a('string')
This is a superficial test.

2020-11-04 13:36 UTC, ceelogre approved these changes

2020-11-04 13:37 UTC, merged