#AO8d4STV Assign buses to routes
atlp-rwanda/cabal-phantom-backend pull request #27
Opened 2020-11-09 15:03 UTC by Niyiragira

### What does this PR do?
It requests to merge ft-assign-buses-to-routes-AO8d4STV into develop
###  Description of Task to be completed?
- Assign registered buses to their 

-Unassign assigned buses from routes
###  How should this be manually tested?

 Any background context you want to provide?
 What are the relevant pivotal tracker stories?
 Screenshots (if appropriate)
 Questions:

2020-11-09 18:02 UTC, ncutixavier approved these changes

2020-11-09 19:23 UTC, Nkbtemmy requested changes
Why. is it your PR have many commits

2020-11-09 19:23 UTC, Nkbtemmy commented on src/middleware/checkExist.js
> +// }
remove this block if it is useless

2020-11-09 19:23 UTC, Nkbtemmy commented on src/test/assignroute.test.js
> +})
new line required

2020-11-09 19:23 UTC, Nkbtemmy commented on src/utils/controlAssignBus.js
> +//import Model from '../database/models'
remove this also

2020-11-11 13:30 UTC, Nkbtemmy approved these changes

2020-11-11 13:30 UTC, Nkbtemmy commented on src/routes/busRoutes.js
> +    checkExist.findRoute,
why don't you have validation here ???

2020-11-11 13:30 UTC, Nkbtemmy commented on src/routes/busRoutes.js
> +    checkExist.findRoute,
Also here need validation of routeID because when routeID is not provide it is also causing server error

2020-11-11 13:30 UTC, Nkbtemmy commented on src/language/locales/en.json
> +}
Add new line here

2020-11-11 13:31 UTC, Nkbtemmy requested changes
Just correct those issues

2020-11-13 06:17 UTC, Nkbtemmy approved these changes

2020-11-17 07:48 UTC, blaise82 requested changes

2020-11-17 07:48 UTC, blaise82 commented on src/controller/busControllers.js
> +            }
make this a middleware

2020-11-17 07:48 UTC, blaise82 commented on src/controller/busControllers.js
> +                    }]
don't fetch again
use updated to return data to be returned


UPDATE: get one bus functionality to include the Route model associated with it

2020-11-17 07:48 UTC, blaise82 commented on src/test/unassignRoute.test.js
> +    });
write more tests

2020-11-17 07:48 UTC, blaise82 commented on src/test/assignRoute.test.js
> +
write a test for if bus not found

2020-11-18 07:29 UTC, karigirwa approved these changes

2020-12-08 07:31 UTC, blaise82 approved these changes

2020-12-08 07:31 UTC, merged