#N4zTfnNuft(backend)-enquire-bus-info
atlp-rwanda/cabal-phantom-backend pull request #28
Opened 2020-11-10 14:27 UTC by karigirwa

**What does this PR do?**
This PR is for Enquire buses info

**Description of Task to be completed?**
 User  should be able to retrieve details of a bus so that he/she can plan his/her next move accordingly.

- User should be able to view the location of bus

- User should be able to view status of the bus

- User should be able to view total number of commuters

- User should be able view the bus type

- User should be able to view available seats

**GET /api/v1/buses/info/:busId**

**How should this be manually tested?**

- You can use Swagger documentation or 

- Use Postman Localhost:5000/api/v1/buses/info/:busId

**What are the relevant pivotal tracker stories?**
[#N4zTfnNuft](https://trello.com/c/N4zTfnNu/16-enquire-buses-info)

2020-11-11 13:36 UTC, Nkbtemmy approved these changes

2020-11-12 07:37 UTC, ncutixavier approved these changes

2020-11-12 08:09 UTC, Niyiragira reviewed
<img width="1440" alt="Screen Shot 2020-11-12 at 10 07 39" src="https://user-images.githubusercontent.com/68019992/98912571-f6f44a80-24ce-11eb-8e3b-f9f4a2bfb64b.png">
For me this endpoint Is not working. Try to check too

2020-11-12 10:36 UTC, Niyiragira approved these changes

2020-11-18 08:16 UTC, ceelogre requested changes
The route should be `/buses/:id` not `/buses/info/:id`

2020-11-18 08:16 UTC, ceelogre commented on src/test/enquireBusInfo.test.js
> +                done()
Inspect the returned object to see the inner content.

2020-11-18 12:06 UTC, ceelogre commented on src/test/enquireBusInfo.test.js
> +                done()
A better name would have been 'buses`, this might confusion when calling the API in the frontend but we can leave it for now.

2020-11-18 12:06 UTC, ceelogre approved these changes

2020-11-18 12:08 UTC, merged